### ISSUE TITLE
Question on calculating HOMO-LUMO gap

### ISSUE THREAD

**Issue by joneswong** [theochem/tinydft#2]
Hi administrators,
    I just have some molecules represented as graphs, where each node( i.e., atom) is characterized by its ID, chirality, etc., each edge is characterized by its bond type, bond stereochemistry, etc.
   Is this information sufficient to use your package to calculate the electron density function?
   Besides, is there any example to use this package to calculate the HOMO-LUMO gap?
   Thanks!

**Comment by tovrstra** [comment]
The scope of TinyDFT is limited to atomic calculations (with the local density approximation) and was mainly written for pedagogical reasons. Molecules are beyond the scope of TinyDFT. Atomic HOMO-LUMO gaps can be deduced from the `evals` arrays, which contain eigenvalues of the Fock Matrix. That said, in the local density approximation, LUMO energies are not very reliable because most local functionals fail to reproduce the Rydberg series.

**Comment by PaulWAyers** [comment]
Local functionals are inherently incapable of getting the correct -1/r decay of the exchange-correlation potential that leads to good Rydberg series and good HOMO-LUMO gaps (for excitation; direct gap) and lack the derivative discontinuity needed needed to model the HOMO-LUMO gap (for electron attachment/ionization; fundamental gap). Computed HOMO/LUMO gaps often correlate pretty well with the true gaps, nonetheless.

There are workflows for converting molecular information into files. Basically one would need to take your input, use a tool like OpenBabel or RDKit to convert it to an *.xyz file, and then from there you could run an external quantum chemistry program. Our IOData package could help with the input-file-generation and parsing the output files for the information you want, then.
    https://iodata.qcdevs.org/
